modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/teaconmc/NeoContinuity"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = """NeoContinuity is an unofficial fork of Continuity, aiming to run Continuity natively on NeoForge and reduce some of the redundant FFAPI dependencies using NeoForge API. Do not report issues encountered with this mod to the original.\n\nContinuity is a Fabric mod that allows resource packs that use the OptiFine connected textures format, OptiFine emissive textures format (only for blocks and item models), or OptiFine custom block layers format to work without OptiFine."""
    logoFile = "assets/continuity/icon.png"
    logoBlur = false
    authors = "${mod_authors}"
    displayURL = "https://modrinth.com/mod/continuity"

[[mixins]]
    config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
